language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - echo $SSH_KEY >> $HOME/.ssh/known_hosts
script: ignore
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 id_rsa
  - ssh-add id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
before_install:
  - openssl aes-256-cbc -K $encrypted_d80d8c724d57_key -iv $encrypted_d80d8c724d57_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar